### ISSUE TITLE
中间的线怎么去掉

### ISSUE THREAD

**Issue by andylidong** [RmondJone/LockTableView#1]
怎么去掉中间的线
![fb0e0d34cb9de006defdad8d6b8a9dc0](https://cloud.githubusercontent.com/assets/18454971/26301438/d85e6d20-3f13-11e7-8956-818eae0c9e48.jpg)

**Comment by RmondJone** [comment]
![default](https://cloud.githubusercontent.com/assets/10555850/26479109/7afa9db4-4203-11e7-9baa-e0819b8f8160.png)

**Comment by lucf1103** [comment]
里面的线是怎么去的？在createScollview的600行设置了，没有反应啊？
