### ISSUE TITLE
45dp的Margin的问题

### ISSUE THREAD

**Issue by Student414** [RmondJone/LockTableView#13]
在平板上调试时，发现存放内容的TextView会有一个45dp的margin，可能是作者考虑到美观方面的问题，才有此设计。但是在我这个平板上显的相当大气，每屏只能展示6x4方块的内容。遂将margin去掉，效果完美，希望作者抽空看看这个点，我感觉45dp有点大~

**Comment by RmondJone** [comment]
已经新增
